/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package questaovinteequatroexercicio;

import java.util.Scanner;

public class App {
   

    public static void main(String[] args) {
        
        Scanner leitor = new Scanner(System.in);
        char desejaContinuar = 'S';
        
        while(desejaContinuar == 'S' || desejaContinuar == 's'){
            
            System.out.println("Digite um numero: ");
            int numero = leitor.nextInt();
            
            if(numero == 0){
                System.out.println("O numero e zero.");
            }else{
                if(numero > 0){
                    System.out.println("O numero e maior que zero.");
                }else{
                    System.out.println("O numero e menor que zero");
                    }
            }
            System.out.println("Deseja continuar? S - Sim / N - Nao");
            desejaContinuar = leitor.next().charAt(0);
        }
        
        
    }
}
