/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Questao4POO;

public class App {
    
    public static void main(String[] args) {
        
        Invoice inv = new Invoice(1, "Teclado", -10, 15.0f);
        System.out.println("Valor total: " + inv.getInvoiceAmount());
        
    }
}
