/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package estruturawhile;

import java.util.Scanner;

public class App {
    

    public static void main(String[] args) {
        
        Scanner leitor = new Scanner(System.in);
        int totalAlunos = 10;
        
        while(totalAlunos >= 10){
            
            String nomeAluno = leitor.next();
            int idadeAluno = leitor.nextInt();
            
            System.out.println("O nome do aluno e: " + nomeAluno + " e sua"
                    + "idade e: " + idadeAluno);
            
            totalAlunos = totalAlunos - 1;
        }
        
    }
}
