/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Questao07POO;

public class App {
    

    public static void main(String[] args) {
       
        Funcionario f1 = new Funcionario("Jairo", "Merces", -1000);
        Funcionario f2 = new Funcionario("Joao", "Victor", 65000);
       // float aumento = 0.10f;
       // int mesesAno = 11;
        
       
        
        System.out.println("Nome: " + f1.getPrimeiroNome());
        System.out.println("Sobrenome: " + f1.getSobrenome());
        System.out.println("Salario Mensal: " + f1.getSalarioMensal());
        System.out.println("Salario Anual sem ajuste: " + f1.demonstrarSalarioAnual());
        System.out.println("==========================================");
        System.out.println("Nome: " + f2.getPrimeiroNome());
        System.out.println("Sobrenome: " + f2.getSobrenome());
        System.out.println("Salario Mensal: " + f2.getSalarioMensal());
        System.out.println("Salario Anual sem ajuste: " + f2.demonstrarSalarioAnual());
        System.out.println("==========================================");
        
        f1.setSalarioMensal(f1.getSalarioMensal() + (f1.getSalarioMensal() * 0.10f));
        f2.setSalarioMensal(f2.getSalarioMensal() + (f2.getSalarioMensal() * 0.10f));
        
        System.out.println("Nome: " + f1.getPrimeiroNome());
        System.out.println("Sobrenome: " + f1.getSobrenome());
        System.out.println("Salario Mensal com ajuste de 10%: " + f1.getSalarioMensal());
        System.out.println("Salario Anual com ajuste de 10%: " + f1.demonstrarSalarioAnual());
        System.out.println("==========================================");
        System.out.println("Nome: " + f2.getPrimeiroNome());
        System.out.println("Sobrenome: " + f2.getSobrenome());
        System.out.println("Salario Mensal com ajuste de 10%: " + f2.getSalarioMensal());
        System.out.println("Salario Anual com ajuste de 10%: " + f2.demonstrarSalarioAnual());
        
    }
}
