/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PrimeiroProjeto;

public class App {
    //public String getGreeting() {
    //    return "Hello World!";
    //}

    public static void main(String[] args) {
        System.out.println("Ola Mundo!");
        System.out.println("Meu primeiro projeto em Java.");
    }
}
